CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name TEXT NOT NULL,
  discord_id TEXT NOT NULL,
  age INTEGER NOT NULL,
  hours INTEGER NOT NULL,
  experience TEXT NOT NULL,
  reason TEXT NOT NULL,
  roleplay TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'pending',
  rejection_reason TEXT,
  reviewed_at TIMESTAMPTZ
);
ALTER TABLE applications ADD COLUMN IF NOT EXISTS previous_gang_name TEXT;
CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications (created_at DESC);
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL UNIQUE REFERENCES applications(id),
  game_name TEXT NOT NULL,
  discord_id TEXT NOT NULL,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_discord_id ON applications (discord_id);
